MakeConstructor(ArrayConstructor, true, ArrayPrototype);
setInternalSlot(ArrayConstructor, SLOTS.CALL, ArrayConstructor_call);
setInternalSlot(ArrayConstructor, SLOTS.CONSTRUCT, ArrayConstructor_construct);
NowDefineBuiltinConstant(ArrayConstructor, "length", 1);
setInternalSlot(ArrayPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
NowDefineBuiltinFunction(ArrayConstructor, $$create, 1, ArrayConstructor_$$create);
NowDefineBuiltinFunction(ArrayConstructor, "from", 1, ArrayConstructor_from);
NowDefineBuiltinFunction(ArrayConstructor, "isArray", 1, ArrayConstructor_isArray);
NowDefineBuiltinFunction(ArrayConstructor, "of", 1, ArrayConstructor_of);
NowDefineBuiltinConstant(ArrayConstructor, "prototype", ArrayPrototype);
NowDefineBuiltinConstant(ArrayConstructor, "prototype", ArrayPrototype);
NowDefineBuiltinFunction(ArrayPrototype, "concat", 1, ArrayPrototype_concat);
NowDefineBuiltinConstant(ArrayPrototype, "constructor", ArrayConstructor);
NowDefineBuiltinFunction(ArrayPrototype, "copyWithin", 2, ArrayPrototype_copyWithin);
NowDefineBuiltinFunction(ArrayPrototype, "entries", 0, ArrayPrototype_entries);
NowDefineBuiltinFunction(ArrayPrototype, "every", 0, ArrayPrototype_every);
NowDefineBuiltinFunction(ArrayPrototype, "fill", 1, ArrayPrototype_fill);
NowDefineBuiltinFunction(ArrayPrototype, "filter", 0, ArrayPrototype_filter);
NowDefineBuiltinFunction(ArrayPrototype, "find", 1, ArrayPrototype_find);
NowDefineBuiltinFunction(ArrayPrototype, "findIndex", 1, ArrayPrototype_findIndex);
NowDefineBuiltinFunction(ArrayPrototype, "first", 1, ArrayPrototype_first);
NowDefineBuiltinFunction(ArrayPrototype, "forEach", 0, ArrayPrototype_forEach);
NowDefineBuiltinFunction(ArrayPrototype, "indexOf", 0, ArrayPrototype_indexOf);
NowDefineBuiltinFunction(ArrayPrototype, "join", 0, ArrayPrototype_join);
NowDefineBuiltinFunction(ArrayPrototype, "keys", 0, ArrayPrototype_keys);
NowDefineBuiltinFunction(ArrayPrototype, "last", 1, ArrayPrototype_last);
NowDefineBuiltinFunction(ArrayPrototype, "lastIndexOf", 0, ArrayPrototype_lastIndexOf);
NowDefineBuiltinFunction(ArrayPrototype, "map", 0, ArrayPrototype_map);
NowDefineBuiltinFunction(ArrayPrototype, "pop", 0, ArrayPrototype_pop);
NowDefineBuiltinFunction(ArrayPrototype, "push", 1, ArrayPrototype_push);
NowDefineBuiltinFunction(ArrayPrototype, "reduce", 1, ArrayPrototype_reduce);
NowDefineBuiltinFunction(ArrayPrototype, "reduceRight", 1, ArrayPrototype_reduceRight);
NowDefineBuiltinFunction(ArrayPrototype, "reverse", 0, ArrayPrototype_reverse);
NowDefineBuiltinFunction(ArrayPrototype, "shift", 0, ArrayPrototype_shift);
NowDefineBuiltinFunction(ArrayPrototype, "slice", 0, ArrayPrototype_slice);
NowDefineBuiltinFunction(ArrayPrototype, "sort", 1, ArrayPrototype_sort);
setInternalSlot(getIntrinsic(INTRINSICS.DEFAULTCOMPARE), SLOTS.CALL, defaultCompareFn_call);
NowDefineBuiltinFunction(ArrayPrototype, "splice", 2, ArrayPrototype_splice);
NowDefineBuiltinFunction(ArrayPrototype, "some", 0, ArrayPrototype_some);
NowDefineBuiltinFunction(ArrayPrototype, "toLocaleString", 2, ArrayPrototype_toLocaleString);
NowDefineBuiltinFunction(ArrayPrototype, "unshift", 1, ArrayPrototype_unshift);
NowDefineProperty(ArrayPrototype, "values", ArrayProto_values);
NowDefineBuiltinConstant(ArrayPrototype, $$toStringTag, "Array");
NowDefineBuiltinFunction(ArrayPrototype, $$iterator, 0, ArrayPrototype_$$iterator);
NowDefineProperty(ArrayPrototype, $$unscopables, (function () {
        var blackList = ObjectCreate();
        CreateDataProperty(blackList, "find", true);
        CreateDataProperty(blackList, "findIndex", true);
        CreateDataProperty(blackList, "fill", true);
        CreateDataProperty(blackList, "copyWithin", true);
        CreateDataProperty(blackList, "entries", true);
        CreateDataProperty(blackList, "keys", true);
        CreateDataProperty(blackList, "values", true);
        return blackList;
}()));
setInternalSlot(ArrayProto_values, SLOTS.CALL, ArrayPrototype_values);
setInternalSlot(ArrayProto_values, SLOTS.CONSTRUCT, undefined);