MakeConstructor(EmitterConstructor, true, EmitterPrototype);
setInternalSlot(EmitterPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
setInternalSlot(EmitterConstructor, SLOTS.CALL, EmitterConstructor_call);
setInternalSlot(EmitterConstructor, SLOTS.CONSTRUCT, EmitterConstructor_construct);
NowDefineBuiltinFunction(EmitterConstructor, $$create, 1, EmitterConstructor_$$create);
NowDefineBuiltinConstant(EmitterConstructor, "prototype", EmitterPrototype);
NowDefineBuiltinConstant(EmitterPrototype, "constructor", EmitterConstructor);
NowDefineBuiltinFunction(EmitterPrototype, "on", 2, EmitterPrototype_on);
NowDefineBuiltinFunction(EmitterPrototype, "once", 2, EmitterPrototype_once);
NowDefineBuiltinFunction(EmitterPrototype, "remove", 2, EmitterPrototype_remove);
NowDefineBuiltinFunction(EmitterPrototype, "removeAll", 2, EmitterPrototype_removeAll);
NowDefineBuiltinFunction(EmitterPrototype, "emit", 2, EmitterPrototype_emit);
NowDefineBuiltinConstant(EmitterPrototype, $$toStringTag, "Emitter");
MakeConstructor(EventConstructor, true, EventPrototype);
MakeConstructor(EventTargetConstructor, true, EventTargetPrototype);
MakeConstructor(MessagePortConstructor, true, MessagePortPrototype);
NowDefineBuiltinFunction(EventTargetPrototype, "addEventListener", 3, EventTargetPrototype_addEventListener);
NowDefineBuiltinFunction(EventTargetPrototype, "dispatchEvent", 1, EventTargetPrototype_dispatchEvent);
NowDefineBuiltinFunction(EventTargetPrototype, "removeEventListener", 2, EventTargetPrototype_removeEventListener);
NowDefineBuiltinFunction(MessagePortPrototype, "close", 0, MessagePortPrototype_close);
NowDefineBuiltinFunction(MessagePortPrototype, "open", 0, MessagePortPrototype_open);
NowDefineBuiltinFunction(MessagePortPrototype, "postMessage", 0, MessagePortPrototype_postMessage);