setInternalSlot(ErrorPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
MakeConstructor(ErrorConstructor, true, ErrorPrototype);
LazyDefineBuiltinConstant(ErrorConstructor, "prototype", ErrorPrototype);
LazyDefineBuiltinConstant(ErrorPrototype, "constructor", ErrorConstructor);
LazyDefineBuiltinConstant(ErrorPrototype, "name", "Error");
setInternalSlot(ErrorConstructor, SLOTS.CALL, ErrorConstructor_call);
setInternalSlot(ErrorConstructor, SLOTS.CONSTRUCT, ErrorConstructor_construct);
LazyDefineBuiltinFunction(ErrorConstructor, $$create, 1, ErrorConstructor_$$create);
LazyDefineBuiltinFunction(ErrorPrototype, "toString", 0, ErrorPrototype_toString);
createNativeError("Syntax", SyntaxErrorConstructor, SyntaxErrorPrototype);
createNativeError("Type", TypeErrorConstructor, TypeErrorPrototype);
createNativeError("Reference", ReferenceErrorConstructor, ReferenceErrorPrototype);
createNativeError("Range", RangeErrorConstructor, RangeErrorPrototype);
createNativeError("URI", URIErrorConstructor, URIErrorPrototype);
createNativeError("Eval", EvalErrorConstructor, EvalErrorPrototype);