MakeConstructor(FunctionConstructor, true, FunctionPrototype);
setInternalSlot(FunctionPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
NowDefineProperty(FunctionPrototype, $$toStringTag, "Function");
NowDefineBuiltinFunction(FunctionPrototype, "valueOf", 0, FunctionPrototype_valueOf);
setInternalSlot(FunctionConstructor, SLOTS.CALL, FunctionConstructor_call);
setInternalSlot(FunctionConstructor, SLOTS.CONSTRUCT, FunctionConstructor_construct);
NowDefineProperty(FunctionConstructor, $$create, CreateBuiltinFunction(realm, FunctionConstructor_$$create, 1, "[Symbol.create]"));
NowDefineProperty(FunctionPrototype, $$create, CreateBuiltinFunction(realm, FunctionPrototype_$$create, 1, "[Symbol.create]"));
NowDefineProperty(FunctionPrototype, "constructor", FunctionConstructor);
NowDefineBuiltinFunction(FunctionPrototype, "toString", 0, FunctionPrototype_toString);
NowDefineBuiltinFunction(FunctionPrototype, "apply", 1, FunctionPrototype_apply);
NowDefineBuiltinFunction(FunctionPrototype, "bind", 1, FunctionPrototype_bind);
NowDefineBuiltinFunction(FunctionPrototype, "call", 1, FunctionPrototype_call);
NowDefineProperty(FunctionPrototype, $$hasInstance, CreateBuiltinFunction(realm, FunctionPrototype_$$hasInstance, 1, "[Symbol.hasInstance]"));
NowDefineBuiltinFunction(FunctionPrototype, "toMethod", 1, FunctionPrototype_toMethod);