setInternalSlot(MapConstructor, SLOTS.PROTOTYPE, FunctionPrototype);
setInternalSlot(MapPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
setInternalSlot(MapConstructor, SLOTS.CALL, MapConstructor_call);
setInternalSlot(MapConstructor, SLOTS.CONSTRUCT, MapConstructor_construct);
NowDefineProperty(MapConstructor, $$create, CreateBuiltinFunction(realm, MapConstructor_$$create, 1, "[Symbol.create]"));
NowDefineBuiltinConstant(MapConstructor, "prototype", MapPrototype);
NowDefineBuiltinFunction(MapPrototype, "get", 1, MapPrototype_get);
NowDefineBuiltinFunction(MapPrototype, "has", 1, MapPrototype_has);
NowDefineBuiltinFunction(MapPrototype, "set", 2, MapPrototype_set);
NowDefineBuiltinFunction(MapPrototype, "delete", 1, MapPrototype_delete);
NowDefineBuiltinConstant(MapPrototype, "constructor", MapConstructor);
NowDefineBuiltinFunction(MapPrototype, "entries", 0, MapPrototype_entries);
NowDefineBuiltinFunction(MapPrototype, "keys", 0, MapPrototype_keys);
NowDefineBuiltinFunction(MapPrototype, "values", 0, MapPrototype_values);
NowDefineBuiltinFunction(MapPrototype, $$iterator, 0, MapPrototype_entries);
NowDefineBuiltinConstant(MapPrototype, $$toStringTag, "Map");