setInternalSlot(MathObject, SLOTS.MATHTAG, true);
setInternalSlot(MathObject, SLOTS.PROTOTYPE, ObjectPrototype);
NowDefineBuiltinConstant(MathObject, "PI", PI);
NowDefineBuiltinConstant(MathObject, "LOG2E", LOG2E);
NowDefineBuiltinConstant(MathObject, "SQRT1_2", SQRT1_2);
NowDefineBuiltinConstant(MathObject, "SQRT2", SQRT2);
NowDefineBuiltinConstant(MathObject, "LN10", LN10);
NowDefineBuiltinConstant(MathObject, "LN2", LN2);
NowDefineBuiltinConstant(MathObject, "E", E);
NowDefineBuiltinConstant(MathObject, "LOG10E", LOG10E);
NowDefineBuiltinConstant(MathObject, $$toStringTag, "Math");
NowDefineBuiltinFunction(MathObject, "atan", 2, MathObject_atan);
NowDefineBuiltinFunction(MathObject, "atan2", 1, MathObject_atan2);
NowDefineBuiltinFunction(MathObject, "ceil", 1, MathObject_ceil);
NowDefineBuiltinFunction(MathObject, "clz", 1, MathObject_clz);
NowDefineBuiltinFunction(MathObject, "cos", 1, MathObject_cos);
NowDefineBuiltinFunction(MathObject, "exp", 1, MathObject_exp);
NowDefineBuiltinFunction(MathObject, "floor", 1, MathObject_floor);
NowDefineBuiltinFunction(MathObject, "hypot", 2, MathObject_hypot);
NowDefineBuiltinFunction(MathObject, "imul", 2, MathObject_imul);
NowDefineBuiltinFunction(MathObject, "log", 1, MathObject_log);
NowDefineBuiltinFunction(MathObject, "log1p", 1, MathObject_log1p);
NowDefineBuiltinFunction(MathObject, "max", 0, MathObject_max);
NowDefineBuiltinFunction(MathObject, "min", 0, MathObject_min);
NowDefineBuiltinFunction(MathObject, "pow", 2, MathObject_pow);
NowDefineBuiltinFunction(MathObject, "sin", 1, MathObject_sin);
NowDefineBuiltinFunction(MathObject, "sign", 1, MathObject_sign);
NowDefineBuiltinFunction(MathObject, "tan", 1, MathObject_tan);
NowDefineBuiltinFunction(MathObject, "random", 0, MathObject_random);