MakeConstructor(NumberConstructor, true, NumberPrototype);
setInternalSlot(NumberConstructor, SLOTS.CALL, NumberConstructor_call);
setInternalSlot(NumberConstructor, SLOTS.CONSTRUCT, NumberConstructor_construct);
NowDefineBuiltinFunction(NumberConstructor, "isFinite", 0, NumberConstructor_isFinite);
NowDefineBuiltinFunction(NumberConstructor, "isNaN", 0, NumberConstructor_isNaN);
NowDefineBuiltinFunction(NumberConstructor, "isInteger", 0, NumberConstructor_isInteger);
NowDefineBuiltinFunction(NumberConstructor, $$create, 0, NumberConstructor_$$create);
NowDefineBuiltinConstant(NumberConstructor, "EPSILON", EPSILON);
NowDefineBuiltinConstant(NumberConstructor, "MIN_INTEGER", MIN_INTEGER);
NowDefineBuiltinConstant(NumberConstructor, "MIN_VALUE", MIN_VALUE);
NowDefineBuiltinConstant(NumberConstructor, "MAX_INTEGER", MAX_INTEGER);
NowDefineBuiltinConstant(NumberConstructor, "MAX_VALUE", MAX_VALUE);
NowDefineBuiltinConstant(NumberConstructor, "NaN", NAN);
NowDefineBuiltinConstant(NumberConstructor, "POSITIVE_INFINITY", POSITIVE_INFINITY);
NowDefineBuiltinConstant(NumberConstructor, "NEGATIVE_INFINITY", NEGATIVE_INFINITY);
NowDefineBuiltinFunction(NumberPrototype, "clz", 0, NumberPrototype_clz);
NowDefineBuiltinFunction(NumberPrototype, "toExponential", 0, NumberPrototype_toExponential);
NowDefineBuiltinFunction(NumberPrototype, "toFixed", 0, NumberPrototype_toFixed);
NowDefineBuiltinFunction(NumberPrototype, "toPrecision", 0, NumberPrototype_toPrecision);
NowDefineBuiltinFunction(NumberPrototype, "toString", 0, NumberPrototype_toString);
NowDefineBuiltinFunction(NumberPrototype, "valueOf", 0, NumberPrototype_valueOf);
NowDefineBuiltinConstant(NumberPrototype, $$toStringTag, "Number");