MakeConstructor(PromiseConstructor, true, PromisePrototype);
setInternalSlot(PromiseConstructor, SLOTS.CALL, PromiseConstructor_call);
setInternalSlot(PromiseConstructor, SLOTS.CONSTRUCT, PromiseConstructor_Construct);
NowDefineProperty(PromiseConstructor, $$create, CreateBuiltinFunction(realm, PromiseConstructor_$$create, 0, "[Symbol.create]"));
NowDefineBuiltinFunction(PromiseConstructor, "resolve", 1, PromiseConstructor_resolve);
NowDefineBuiltinFunction(PromiseConstructor, "reject", 1, PromiseConstructor_reject);
NowDefineBuiltinFunction(PromiseConstructor, "cast", 1, PromiseConstructor_cast);
NowDefineBuiltinFunction(PromiseConstructor, "race", 1, PromiseConstructor_race);
NowDefineProperty(PromiseConstructor, "all", CreateBuiltinFunction(realm, PromiseConstructor_all, 0, "all"));
NowDefineProperty(PromisePrototype, "then", CreateBuiltinFunction(realm, PromisePrototype_then, 2, "then"));
NowDefineProperty(PromisePrototype, "catch", CreateBuiltinFunction(realm, PromisePrototype_catch, 1, "catch"));
NowDefineProperty(PromisePrototype, "constructor", PromiseConstructor);
NowDefineProperty(PromisePrototype, $$toStringTag, "Promise");