NowDefineBuiltinFunction(ReflectObject, "defineProperty", 2, ReflectObject_defineProperty);
NowDefineBuiltinFunction(ReflectObject, "deleteProperty", 3, ReflectObject_deleteProperty);
NowDefineBuiltinFunction(ReflectObject, "enumerate", 1, ReflectObject_enumerate);
NowDefineBuiltinFunction(ReflectObject, "invoke", 3, ReflectObject_invoke);
NowDefineBuiltinFunction(ReflectObject, "isExtensible", 1, ReflectObject_isExtensible);
NowDefineBuiltinFunction(ReflectObject, "get", 2, ReflectObject_get);
NowDefineBuiltinFunction(ReflectObject, "getOwnPropertyDescriptor", 2, ReflectObject_getOwnPropertyDescriptor);
NowDefineBuiltinFunction(ReflectObject, "getPrototypeOf", 1, ReflectObject_getPrototypeOf);
NowDefineBuiltinFunction(ReflectObject, "has", 2, ReflectObject_has);
NowDefineBuiltinFunction(ReflectObject, "hasOwn", 2, ReflectObject_hasOwn);
NowDefineProperty(ReflectObject, SLOTS.LOADER, LoaderConstructor);
NowDefineBuiltinFunction(ReflectObject, "ownKeys", 1, ReflectObject_ownKeys);
NowDefineBuiltinFunction(ReflectObject, "parse", 1, ReflectObject_parse);
NowDefineBuiltinFunction(ReflectObject, "parseGoal", 1, ReflectObject_parseGoal);
NowDefineBuiltinFunction(ReflectObject, "preventExtensions", 1, ReflectObject_preventExtensions);
NowDefineProperty(ReflectObject, SLOTS.REALM, RealmConstructor);
NowDefineBuiltinFunction(ReflectObject, "set", 3, ReflectObject_set);
NowDefineBuiltinFunction(ReflectObject, "setPrototypeOf", 2, ReflectObject_setPrototypeOf);
NowDefineBuiltinConstant(ReflectObject, $$toStringTag, "Reflect");
NowDefineBuiltinFunction(ReflectObject, "getIntrinsic", 1, ReflectObject_getIntrinsic);
NowDefineBuiltinFunction(ReflectObject, "createSelfHostingFunction", 2, ReflectObject_createSelfHostingFunction);