LazyDefineBuiltinFunction(ReflectObject, "defineProperty", 2, ReflectObject_defineProperty);
LazyDefineBuiltinFunction(ReflectObject, "deleteProperty", 3, ReflectObject_deleteProperty);
LazyDefineBuiltinFunction(ReflectObject, "enumerate", 1, ReflectObject_enumerate);
LazyDefineBuiltinFunction(ReflectObject, "invoke", 3, ReflectObject_invoke);
LazyDefineBuiltinFunction(ReflectObject, "isExtensible", 1, ReflectObject_isExtensible);
LazyDefineBuiltinFunction(ReflectObject, "get", 2, ReflectObject_get);
LazyDefineBuiltinFunction(ReflectObject, "getOwnPropertyDescriptor", 2, ReflectObject_getOwnPropertyDescriptor);
LazyDefineBuiltinFunction(ReflectObject, "getPrototypeOf", 1, ReflectObject_getPrototypeOf);
LazyDefineBuiltinFunction(ReflectObject, "has", 2, ReflectObject_has);
LazyDefineBuiltinFunction(ReflectObject, "hasOwn", 2, ReflectObject_hasOwn);
LazyDefineProperty(ReflectObject, SLOTS.LOADER, LoaderConstructor);
LazyDefineBuiltinFunction(ReflectObject, "ownKeys", 1, ReflectObject_ownKeys);
LazyDefineBuiltinFunction(ReflectObject, "parse", 1, ReflectObject_parse);
LazyDefineBuiltinFunction(ReflectObject, "parseGoal", 1, ReflectObject_parseGoal);
LazyDefineBuiltinFunction(ReflectObject, "preventExtensions", 1, ReflectObject_preventExtensions);
LazyDefineProperty(ReflectObject, SLOTS.REALM, RealmConstructor);
LazyDefineBuiltinFunction(ReflectObject, "set", 3, ReflectObject_set);
LazyDefineBuiltinFunction(ReflectObject, "setPrototypeOf", 2, ReflectObject_setPrototypeOf);
LazyDefineBuiltinConstant(ReflectObject, $$toStringTag, "Reflect");
LazyDefineBuiltinFunction(ReflectObject, "getIntrinsic", 1, ReflectObject_getIntrinsic);
LazyDefineBuiltinFunction(ReflectObject, "createSelfHostingFunction", 2, ReflectObject_createSelfHostingFunction);