MakeConstructor(RegExpConstructor, true, RegExpPrototype);
setInternalSlot(RegExpConstructor, SLOTS.CALL, RegExp_Call);
setInternalSlot(RegExpConstructor, SLOTS.CONSTRUCT, RegExp_Construct);
NowDefineBuiltinConstant(RegExpConstructor, "prototype", RegExpPrototype);
NowDefineBuiltinConstant(RegExpPrototype, "constructor", RegExpConstructor);
NowDefineBuiltinConstant(RegExpPrototype, $$isRegExp, true);
NowDefineBuiltinConstant(RegExpPrototype, $$toStringTag, "RegExp");
NowDefineBuiltinFunction(RegExpConstructor, $$create, 1, RegExp_$$create);
NowDefineAccessorFunction(RegExpPrototype, "ignoreCase",  0, RegExpPrototype_get_ignoreCase);
NowDefineAccessorFunction(RegExpPrototype, "global",  0, RegExpPrototype_get_global);
NowDefineAccessorFunction(RegExpPrototype, "multiline",  0, RegExpPrototype_get_multiline);
NowDefineAccessorFunction(RegExpPrototype, "source",  0, RegExpPrototype_get_source);
NowDefineAccessorFunction(RegExpPrototype, "sticky",  0, RegExpPrototype_get_sticky);
NowDefineAccessorFunction(RegExpPrototype, "unicode", 0, RegExpPrototype_get_unicode);
NowDefineProperty(RegExpPrototype, "lastIndex", 0);
NowDefineBuiltinFunction(RegExpPrototype, "compile", 1, RegExpPrototype_compile);
NowDefineBuiltinFunction(RegExpPrototype, "exec", 1, RegExpPrototype_exec);
NowDefineBuiltinFunction(RegExpPrototype, "match", 1, RegExpPrototype_match);
NowDefineBuiltinFunction(RegExpPrototype, "replace", 1, RegExpPrototype_replace);
NowDefineBuiltinFunction(RegExpPrototype, "search", 1, RegExpPrototype_search);
NowDefineBuiltinFunction(RegExpPrototype, "split", 1, RegExpPrototype_split);
NowDefineBuiltinFunction(RegExpPrototype, "test", 1, RegExpPrototype_test);
NowDefineBuiltinFunction(RegExpPrototype, "toString", 1, RegExpPrototype_toString);