setInternalSlot(SetConstructor, SLOTS.PROTOTYPE, FunctionPrototype);
setInternalSlot(SetPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
setInternalSlot(SetConstructor, SLOTS.CALL, SetConstructor_call);
setInternalSlot(SetConstructor, SLOTS.CONSTRUCT, SetConstructor_construct);
NowDefineProperty (SetConstructor, $$create, CreateBuiltinFunction(realm, SetConstructor_$$create, 1, "[Symbol.create]"));
NowDefineBuiltinConstant(SetPrototype, $$toStringTag, "Set");
NowDefineBuiltinFunction(SetPrototype, "clear", 0, SetPrototype_clear);
NowDefineBuiltinFunction(SetPrototype, "set", 1, SetPrototype_set);
NowDefineBuiltinFunction(SetPrototype, "has", 1, SetPrototype_has);
NowDefineBuiltinFunction(SetPrototype, "delete", 1, SetPrototype_delete);
NowDefineBuiltinFunction(SetPrototype, "keys", 0, SetPrototype_keys);
NowDefineBuiltinFunction(SetPrototype, "values", 0, SetPrototype_values);
NowDefineBuiltinFunction(SetPrototype, "entries", 0, SetPrototype_entries);
NowDefineBuiltinFunction(SetPrototype, "forEach", 0, SetPrototype_forEach);
NowDefineBuiltinFunction(SetPrototype, $$iterator, 0, SetPrototype_values);