setInternalSlot(SetConstructor, SLOTS.PROTOTYPE, FunctionPrototype);
setInternalSlot(SetPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
setInternalSlot(SetConstructor, SLOTS.CALL, SetConstructor_call);
setInternalSlot(SetConstructor, SLOTS.CONSTRUCT, SetConstructor_construct);
LazyDefineProperty (SetConstructor, $$create, CreateBuiltinFunction(realm, SetConstructor_$$create, 1, "[Symbol.create]"));
LazyDefineBuiltinConstant(SetPrototype, $$toStringTag, "Set");
LazyDefineBuiltinFunction(SetPrototype, "clear", 0, SetPrototype_clear);
LazyDefineBuiltinFunction(SetPrototype, "set", 1, SetPrototype_set);
LazyDefineBuiltinFunction(SetPrototype, "has", 1, SetPrototype_has);
LazyDefineBuiltinFunction(SetPrototype, "delete", 1, SetPrototype_delete);
LazyDefineBuiltinFunction(SetPrototype, "keys", 0, SetPrototype_keys);
LazyDefineBuiltinFunction(SetPrototype, "values", 0, SetPrototype_values);
LazyDefineBuiltinFunction(SetPrototype, "entries", 0, SetPrototype_entries);
LazyDefineBuiltinFunction(SetPrototype, "forEach", 0, SetPrototype_forEach);
LazyDefineBuiltinFunction(SetPrototype, $$iterator, 0, SetPrototype_values);