MakeConstructor(StringConstructor, true, StringPrototype);
setInternalSlot(StringConstructor, SLOTS.CALL, StringConstructor_call);
setInternalSlot(StringConstructor, SLOTS.CONSTRUCT, StringConstructor_construct);
LazyDefineBuiltinFunction(StringConstructor, "raw", 1, StringConstructor_raw);
LazyDefineBuiltinFunction(StringConstructor, $$create, 1, StringConstructor_$$create);
LazyDefineBuiltinFunction(StringPrototype, "at", 1, StringPrototype_at);
LazyDefineBuiltinFunction(StringPrototype, "charAt", 1, StringPrototype_charAt);
LazyDefineBuiltinFunction(StringPrototype, "charCodeAt", 1, StringPrototype_charCodeAt);
LazyDefineBuiltinFunction(StringPrototype, "codePointAt", 1, StringPrototype_codePointAt);
LazyDefineBuiltinFunction(StringPrototype, "concat", 1, StringPrototype_concat);
LazyDefineBuiltinFunction(StringPrototype, "contains", 1, StringPrototype_contains);
LazyDefineBuiltinFunction(StringPrototype, "endsWith", 1, StringPrototype_endsWith);
LazyDefineBuiltinFunction(StringPrototype, "indexOf", 1, StringPrototype_indexOf);
LazyDefineBuiltinFunction(StringPrototype, "lastIndexOf", 1, StringPrototype_lastIndexOf);
LazyDefineBuiltinFunction(StringPrototype, "lpad", 1, StringPrototype_lpad);
LazyDefineBuiltinFunction(StringPrototype, "rpad", 1, StringPrototype_rpad);
LazyDefineBuiltinFunction(StringPrototype, "match", 0, StringPrototype_match);
LazyDefineBuiltinFunction(StringPrototype, "normalize", 0, StringPrototype_normalize);
LazyDefineBuiltinFunction(StringPrototype, "repeat", 0, StringPrototype_repeat);
LazyDefineBuiltinFunction(StringPrototype, "replace", 0, StringPrototype_replace);
LazyDefineBuiltinFunction(StringPrototype, "search", 1, StringPrototype_search);
LazyDefineBuiltinFunction(StringPrototype, "startsWith", 1, StringPrototype_startsWith);
LazyDefineBuiltinFunction(StringPrototype, "toArray", 0, StringPrototype_toArray);
LazyDefineBuiltinFunction(StringPrototype, "toLocaleCompare", 0, StringPrototype_localeCompare);
LazyDefineBuiltinFunction(StringPrototype, "toLowerCase", 0, StringPrototype_toLowerCase);
LazyDefineBuiltinFunction(StringPrototype, "toUpperCase", 0, StringPrototype_toUpperCase);
LazyDefineBuiltinFunction(StringPrototype, "trim", 1, StringPrototype_trim);
LazyDefineBuiltinFunction(StringPrototype, "valueOf", 0, StringPrototype_valueOf);
LazyDefineBuiltinConstant(StringPrototype, $$toStringTag, "String");
LazyDefineBuiltinFunction(StringPrototype, $$iterator, 0, StringPrototype_$$iterator);
LazyDefineBuiltinFunction(StringPrototype, "entries", 0, StringPrototype_entries);
LazyDefineBuiltinFunction(StringPrototype, "keys", 0, StringPrototype_keys);
LazyDefineBuiltinFunction(StringPrototype, "values", 0, StringPrototype_values);
