MakeConstructor(StringConstructor, true, StringPrototype);
setInternalSlot(StringConstructor, SLOTS.CALL, StringConstructor_call);
setInternalSlot(StringConstructor, SLOTS.CONSTRUCT, StringConstructor_construct);
NowDefineBuiltinFunction(StringConstructor, "raw", 1, StringConstructor_raw);
NowDefineBuiltinFunction(StringConstructor, $$create, 1, StringConstructor_$$create);

NowDefineBuiltinFunction(StringConstructor, "fromCharCode", 1, StringConstructor_fromCharCode);
NowDefineBuiltinFunction(StringConstructor, "fromCodePoint", 1, StringConstructor_fromCodePoint);
NowDefineBuiltinFunction(StringConstructor, "raw", 1, StringConstructor_raw);

NowDefineBuiltinFunction(StringPrototype, "at", 1, StringPrototype_at);
NowDefineBuiltinFunction(StringPrototype, "charAt", 1, StringPrototype_charAt);
NowDefineBuiltinFunction(StringPrototype, "charCodeAt", 1, StringPrototype_charCodeAt);
NowDefineBuiltinFunction(StringPrototype, "codePointAt", 1, StringPrototype_codePointAt);
NowDefineBuiltinFunction(StringPrototype, "concat", 1, StringPrototype_concat);
NowDefineBuiltinFunction(StringPrototype, "contains", 1, StringPrototype_contains);
NowDefineBuiltinFunction(StringPrototype, "endsWith", 1, StringPrototype_endsWith);
NowDefineBuiltinFunction(StringPrototype, "indexOf", 1, StringPrototype_indexOf);
NowDefineBuiltinFunction(StringPrototype, "lastIndexOf", 1, StringPrototype_lastIndexOf);
NowDefineBuiltinFunction(StringPrototype, "lpad", 1, StringPrototype_lpad);
NowDefineBuiltinFunction(StringPrototype, "rpad", 1, StringPrototype_rpad);
NowDefineBuiltinFunction(StringPrototype, "match", 0, StringPrototype_match);
NowDefineBuiltinFunction(StringPrototype, "normalize", 0, StringPrototype_normalize);
NowDefineBuiltinFunction(StringPrototype, "repeat", 0, StringPrototype_repeat);
NowDefineBuiltinFunction(StringPrototype, "replace", 0, StringPrototype_replace);
NowDefineBuiltinFunction(StringPrototype, "search", 1, StringPrototype_search);
NowDefineBuiltinFunction(StringPrototype, "startsWith", 1, StringPrototype_startsWith);
NowDefineBuiltinFunction(StringPrototype, "toArray", 0, StringPrototype_toArray);
NowDefineBuiltinFunction(StringPrototype, "toLocaleCompare", 0, StringPrototype_localeCompare);
NowDefineBuiltinFunction(StringPrototype, "toLowerCase", 0, StringPrototype_toLowerCase);
NowDefineBuiltinFunction(StringPrototype, "toUpperCase", 0, StringPrototype_toUpperCase);
NowDefineBuiltinFunction(StringPrototype, "toString", 0, StringPrototype_toString);
NowDefineBuiltinFunction(StringPrototype, "trim", 1, StringPrototype_trim);
NowDefineBuiltinFunction(StringPrototype, "valueOf", 0, StringPrototype_valueOf);
NowDefineBuiltinConstant(StringPrototype, $$toStringTag, "String");
NowDefineBuiltinFunction(StringPrototype, $$iterator, 0, StringPrototype_$$iterator);
NowDefineBuiltinFunction(StringPrototype, "entries", 0, StringPrototype_entries);
NowDefineBuiltinFunction(StringPrototype, "keys", 0, StringPrototype_keys);
NowDefineBuiltinFunction(StringPrototype, "values", 0, StringPrototype_values);