MakeConstructor(SymbolFunction, true, SymbolPrototype);
setInternalSlot(SymbolFunction, SLOTS.CALL, SymbolFunction_Call);
setInternalSlot(SymbolFunction, SLOTS.CONSTRUCT, SymbolFunction_Construct);
setInternalSlot(SymbolPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
LazyDefineBuiltinConstant(SymbolFunction, $$create, CreateBuiltinFunction(realm, SymbolFunction_$$create, 0, "[Symbol.create]"));
LazyDefineBuiltinConstant(SymbolFunction, "create", $$create);
LazyDefineBuiltinFunction(SymbolFunction, "for", 1, SymbolFunction_for);
LazyDefineBuiltinConstant(SymbolFunction, "isConcatSpreadable", $$isConcatSpreadable);
LazyDefineBuiltinConstant(SymbolFunction, "isRegExp", $$isRegExp);
LazyDefineBuiltinConstant(SymbolFunction, "iterator", $$iterator);
LazyDefineBuiltinFunction(SymbolFunction, "keyFor", 1, SymbolFunction_keyFor);
LazyDefineBuiltinConstant(SymbolFunction, "prototype", SymbolPrototype);
LazyDefineBuiltinConstant(SymbolFunction, "hasInstance", $$hasInstance);
LazyDefineBuiltinConstant(SymbolFunction, "toPrimitive", $$toPrimitive);
LazyDefineBuiltinConstant(SymbolFunction, "toStringTag", $$toStringTag);
LazyDefineBuiltinConstant(SymbolFunction, "unscopables", $$unscopables);
LazyDefineBuiltinConstant(SymbolPrototype, "constructor", SymbolFunction);
LazyDefineBuiltinConstant(SymbolPrototype, $$toPrimitive, CreateBuiltinFunction(realm, SymbolPrototype_$$toPrimitive, 1, "[Symbol.toPrimitive]"));
LazyDefineBuiltinFunction(SymbolPrototype, "toString", 0, SymbolPrototype_toString);
LazyDefineBuiltinConstant(SymbolPrototype, $$toStringTag, "Symbol");
LazyDefineBuiltinFunction(SymbolPrototype, "valueOf", 0, SymbolPrototype_valueOf);
