MakeConstructor(SymbolFunction, true, SymbolPrototype);
setInternalSlot(SymbolFunction, SLOTS.CALL, SymbolFunction_Call);
setInternalSlot(SymbolFunction, SLOTS.CONSTRUCT, SymbolFunction_Construct);
setInternalSlot(SymbolPrototype, SLOTS.PROTOTYPE, ObjectPrototype);
NowDefineBuiltinConstant(SymbolFunction, $$create, CreateBuiltinFunction(realm, SymbolFunction_$$create, 0, "[Symbol.create]"));
NowDefineBuiltinConstant(SymbolFunction, "create", $$create);
NowDefineBuiltinFunction(SymbolFunction, "for", 1, SymbolFunction_for);
NowDefineBuiltinConstant(SymbolFunction, "isConcatSpreadable", $$isConcatSpreadable);
NowDefineBuiltinConstant(SymbolFunction, "isRegExp", $$isRegExp);
NowDefineBuiltinConstant(SymbolFunction, "iterator", $$iterator);
NowDefineBuiltinFunction(SymbolFunction, "keyFor", 1, SymbolFunction_keyFor);
NowDefineBuiltinConstant(SymbolFunction, "prototype", SymbolPrototype);
NowDefineBuiltinConstant(SymbolFunction, "hasInstance", $$hasInstance);
NowDefineBuiltinConstant(SymbolFunction, "toPrimitive", $$toPrimitive);
NowDefineBuiltinConstant(SymbolFunction, "toStringTag", $$toStringTag);
NowDefineBuiltinConstant(SymbolFunction, "unscopables", $$unscopables);
NowDefineBuiltinConstant(SymbolPrototype, "constructor", SymbolFunction);
NowDefineBuiltinConstant(SymbolPrototype, $$toPrimitive, CreateBuiltinFunction(realm, SymbolPrototype_$$toPrimitive, 1, "[Symbol.toPrimitive]"));
NowDefineBuiltinFunction(SymbolPrototype, "toString", 0, SymbolPrototype_toString);
NowDefineBuiltinConstant(SymbolPrototype, $$toStringTag, "Symbol");
NowDefineBuiltinFunction(SymbolPrototype, "valueOf", 0, SymbolPrototype_valueOf);