/**
 * Created by root on 10.05.14.
 */

var INTRINSICS = Object.create(null);
INTRINSICS.OBJECT = "%Object%";
INTRINSICS.OBJECTPROTOTYPE = "%ObjectPrototype%";
INTRINSICS.FUNCTION = "%Function%";
INTRINSICS.FUNCTIONPROTOTYPE = "%FunctionPrototype%";
INTRINSICS.ARRAY = "%Array%";
INTRINSICS.ARRAYPROTOTYPE = "%ArrayPrototype%";
INTRINSICS.ARRAYITERATORPROTOTYPE = "%ArrayIteratorPrototype%";
INTRINSICS.GENERATOR = "%Generator%";
INTRINSICS.GENERATORPROTOTYPE = "%GeneratorPrototype%";
INTRINSICS.MATH = "%Math%";
INTRINSICS.JSON = "%JSON%";
INTRINSICS.REFLECT = "%Reflect%";
INTRINSICS.LOADER = "%Loader%";
INTRINSICS.LOADERPROTOTYPE = "%LoaderPrototype%";
INTRINSICS.LOADERITERATORPROTOTYPE = "%LoaderIteratorPrototype%";

Object.freeze(INTRINSICS);
