/**
 * Created by root on 10.05.14.
 */

var INTRINSICS = Object.create(null);

INTRINSICS.OBJECT = "%Object%";
INTRINSICS.OBJECTPROTOTYPE = "%ObjectPrototype%";
INTRINSICS.FUNCTION = "%Function%";
INTRINSICS.FUNCTIONPROTOTYPE = "%FunctionPrototype%";
INTRINSICS.ARRAY = "%Array%";
INTRINSICS.ARRAYPROTOTYPE = "%ArrayPrototype%";
INTRINSICS.ARRAYITERATORPROTOTYPE = "%ArrayIteratorPrototype%";
INTRINSICS.GENERATOR = "%Generator%";
INTRINSICS.GENERATORPROTOTYPE = "%GeneratorPrototype%";
INTRINSICS.MATH = "%Math%";
INTRINSICS.JSON = "%JSON%";
INTRINSICS.REFLECT = "%Reflect%";
INTRINSICS.LOADER = "%Loader%";
INTRINSICS.LOADERPROTOTYPE = "%LoaderPrototype%";
INTRINSICS.LOADERITERATORPROTOTYPE = "%LoaderIteratorPrototype%";
INTRINSICS.GENERATORFUNCTION = "%GeneratorFunction%";
INTRINSICS.ARRAYBUFFER = "%ArrayBuffer%";
INTRINSICS.ARRAYBUFFERPROTOTYPE = "%ArrayBufferPrototype%";
INTRINSICS.DATAVIEW = "%DataView%";
INTRINSICS.DATAVIEWPROTOTYPE = "%DataViewPrototype%";
INTRINSICS.ERROR = "%Error%";
INTRINSICS.ERRORPROTOTYPE = "%ErrorPrototype%";
INTRINSICS.TYPEERROR = "%TypeError%";
INTRINSICS.TYPEERRORPROTOTYPE = "%TypeErrorPrototype%";
INTRINSICS.REFERENCEERROR = "%ReferenceError%";
INTRINSICS.REFERENCEERRORPROTOTYPE = "%ReferenceErrorPrototype%";
Object.freeze(INTRINSICS);
